name: Select Merged PR
description: 'Permite al usuario seleccionar un PR mergeado'
inputs:
  token:
    description: 'Token de GitHub'
    required: true
outputs:
  selected_pr_number:
    description: 'Número del PR seleccionado'
    value: ${{ steps.response.outputs.selected_pr_number }}
runs:
  using: 'composite'
  steps:
    - run: echo "Iniciando selección de PR mergeado"
      shell: bash
    - id: response
      shell: bash
      run: |
        # Aquí puedes implementar la lógica para mostrar una interfaz de usuario donde el usuario pueda seleccionar un PR mergeado
        # Luego, envía el número del PR seleccionado como una respuesta
        echo "::set-output name=selected_pr_number::123"  # Aquí debes sustituir "123" por el número del PR seleccionado por el usuario
